# Generated by Django 4.0.2 on 2022-02-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.JSONField(unique=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
