# Generated by Django 4.0.2 on 2022-02-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        ('type', '0003_init'),
    ]
    operations = [
        migrations.RunSQL("INSERT INTO type_type (id, name) VALUES (1, 'table')"),
        migrations.RunSQL("INSERT INTO type_type (id, name) VALUES (2, 'comments')")
    ]


