# Generated by Django 4.0.2 on 2022-02-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_string', models.CharField(db_index=True, max_length=255, unique=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey('authentication.User', on_delete=models.RESTRICT, null=False)),
                ('metadata', models.ForeignKey('metadata.Metadata', on_delete=models.RESTRICT, null=False)),
            ],
            options={
                'abstract': False,
            },
        ),

    ]

