# Generated by Django 4.0.2 on 2022-02-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='Spider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
